package core

import (
	"bytes"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base32"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/url"
	"strings"
	"time"
)

func (a *ERPAuthenticator) WerkaArchivePDF(ctx context.Context, principal Principal, kind WerkaArchiveKind, period WerkaArchivePeriod) (GeneratedFile, error) {
	report, err := a.WerkaArchive(ctx, kind, period)
	if err != nil {
		return GeneratedFile{}, err
	}
	reportID := buildArchiveReportID(kind)
	verifyCode, err := buildArchiveVerifyCode()
	if err != nil {
		return GeneratedFile{}, err
	}
	datasetHash, err := buildArchiveDatasetHash(report)
	if err != nil {
		return GeneratedFile{}, err
	}
	if a.reportExports != nil {
		if err := a.reportExports.Put(ReportExportRecord{
			ReportID:        reportID,
			VerifyCode:      verifyCode,
			Kind:            kind,
			Period:          period,
			From:            report.From,
			To:              report.To,
			GeneratedAt:     time.Now().UTC(),
			GeneratedByRole: principal.Role,
			GeneratedByRef:  strings.TrimSpace(principal.Ref),
			GeneratedByName: strings.TrimSpace(principal.DisplayName),
			DatasetHash:     datasetHash,
			RecordCount:     report.Summary.RecordCount,
		}); err != nil {
			return GeneratedFile{}, err
		}
	}
	verifyURL := buildArchiveVerifyURL(reportID, verifyCode)
	body, err := renderWerkaArchivePDF(principal, report, reportID, verifyCode, verifyURL)
	if err != nil {
		return GeneratedFile{}, err
	}
	return GeneratedFile{
		Filename:    fmt.Sprintf("werka-%s-%s-%s.pdf", kind, period, time.Now().Format("2006-01-02")),
		ContentType: "application/pdf",
		Body:        body,
	}, nil
}

func (a *ERPAuthenticator) VerifyArchiveReport(reportID, verifyCode string) (ReportVerifyResponse, error) {
	if a.reportExports == nil {
		return ReportVerifyResponse{Valid: false, Status: "not_configured"}, nil
	}
	record, err := a.reportExports.Get(strings.TrimSpace(reportID))
	if err != nil {
		return ReportVerifyResponse{}, err
	}
	if strings.TrimSpace(record.ReportID) == "" {
		return ReportVerifyResponse{
			Valid:  false,
			Status: "not_found",
		}, nil
	}
	if strings.TrimSpace(record.VerifyCode) != strings.TrimSpace(verifyCode) {
		return ReportVerifyResponse{
			Valid:    false,
			Status:   "invalid_code",
			ReportID: record.ReportID,
		}, nil
	}
	return ReportVerifyResponse{
		Valid:           true,
		Status:          "valid",
		ReportID:        record.ReportID,
		VerifyCode:      record.VerifyCode,
		Kind:            record.Kind,
		Period:          record.Period,
		From:            record.From,
		To:              record.To,
		GeneratedAt:     record.GeneratedAt,
		GeneratedByRole: record.GeneratedByRole,
		GeneratedByRef:  record.GeneratedByRef,
		GeneratedByName: record.GeneratedByName,
		DatasetHash:     record.DatasetHash,
		RecordCount:     record.RecordCount,
	}, nil
}

func renderWerkaArchivePDF(principal Principal, report WerkaArchiveResponse, reportID, verifyCode, verifyURL string) ([]byte, error) {
	title := archiveReportTitle(report.Kind)
	period := archivePeriodTitle(report.Period)
	generatedAt := time.Now().In(report.From.Location()).Format("2006-01-02 15:04:05")
	generatedBy := strings.TrimSpace(principal.DisplayName)
	if generatedBy == "" {
		generatedBy = strings.TrimSpace(principal.Ref)
	}
	if generatedBy == "" {
		generatedBy = "Werka"
	}

	lines := []pdfLine{
		{text: "ACCORD ARCHIVE REPORT", bold: true, fontSize: 18},
		{text: title, bold: true, fontSize: 16},
		{text: "Period: " + period, fontSize: 11},
		{text: "Oraliq: " + report.From.Format("2006-01-02 15:04") + " -> " + report.To.Format("2006-01-02 15:04"), fontSize: 11},
		{text: "Generated at: " + generatedAt, fontSize: 11},
		{text: "Generated by: " + generatedBy + " (" + strings.TrimSpace(string(principal.Role)) + ")", fontSize: 11},
		{text: "Report ID: " + reportID, fontSize: 11},
		{text: "Verify code: " + verifyCode, fontSize: 11},
		{text: truncatePDFLine("Verify URL: "+verifyURL, 110), fontSize: 9},
		{text: "", fontSize: 8},
		{text: fmt.Sprintf("Yozuvlar soni: %d", report.Summary.RecordCount), bold: true, fontSize: 12},
	}

	if len(report.Summary.TotalsByUOM) > 0 {
		for _, total := range report.Summary.TotalsByUOM {
			lines = append(lines, pdfLine{
				text:     fmt.Sprintf("Jami: %s %.2f", strings.TrimSpace(total.UOM), total.Qty),
				fontSize: 11,
			})
		}
	}

	lines = append(lines,
		pdfLine{text: "", fontSize: 8},
		pdfLine{text: "Sana | Hujjat | Counterparty | Mahsulot | Miqdor | Status", bold: true, fontSize: 11},
	)

	for _, item := range report.Items {
		lines = append(lines,
			pdfLine{
				text: truncatePDFLine(
					fmt.Sprintf(
						"%s | %s | %s | %s | %.2f %s | %s",
						item.CreatedLabel,
						item.ID,
						item.SupplierName,
						item.ItemCode,
						archiveQtyForKind(report.Kind, item),
						item.UOM,
						item.Status,
					),
					110,
				),
				fontSize: 10,
			},
			pdfLine{
				text:     truncatePDFLine("Item name: "+item.ItemName, 110),
				fontSize: 9,
			},
		)
	}

	lines = append(lines,
		pdfLine{text: "", fontSize: 8},
		pdfLine{text: "Protected static PDF • watermark • report id • verify code", fontSize: 9},
	)

	return buildStaticPDF(lines, "ACCORD ARCHIVE"), nil
}

func buildArchiveDatasetHash(report WerkaArchiveResponse) (string, error) {
	payload, err := json.Marshal(report)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(payload)
	return hex.EncodeToString(sum[:]), nil
}

func buildArchiveVerifyURL(reportID, verifyCode string) string {
	return "https://core.wspace.sbs/v1/mobile/werka/archive/pdf/verify?id=" +
		url.QueryEscape(strings.TrimSpace(reportID)) +
		"&code=" + url.QueryEscape(strings.TrimSpace(verifyCode))
}

type pdfLine struct {
	text     string
	fontSize int
	bold     bool
}

func buildStaticPDF(lines []pdfLine, watermark string) []byte {
	const (
		pageWidth   = 595
		pageHeight  = 842
		leftMargin  = 42
		topStartY   = 800
		bottomLimit = 50
	)

	pages := make([][]pdfLine, 0, 4)
	current := make([]pdfLine, 0, 48)
	y := topStartY
	for _, line := range lines {
		step := 14
		if line.fontSize >= 16 {
			step = 22
		} else if line.fontSize >= 12 {
			step = 18
		} else if line.fontSize <= 9 {
			step = 12
		}
		if y-step < bottomLimit && len(current) > 0 {
			pages = append(pages, current)
			current = make([]pdfLine, 0, 48)
			y = topStartY
		}
		current = append(current, line)
		y -= step
	}
	if len(current) > 0 {
		pages = append(pages, current)
	}

	maxID := 4 + len(pages)*2
	objects := make([]string, maxID+1)
	objects[1] = "<< /Type /Catalog /Pages 2 0 R >>"

	kids := make([]string, 0, len(pages))
	for pageIndex, pageLines := range pages {
		pageID := 5 + pageIndex*2
		contentID := pageID + 1
		kids = append(kids, fmt.Sprintf("%d 0 R", pageID))
		content := buildPDFContent(pageLines, watermark, pageIndex+1, len(pages), leftMargin, topStartY)
		objects[pageID] = fmt.Sprintf("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 %d %d] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents %d 0 R >>", pageWidth, pageHeight, contentID)
		objects[contentID] = fmt.Sprintf("<< /Length %d >>\nstream\n%s\nendstream", len(content), content)
	}
	objects[2] = fmt.Sprintf("<< /Type /Pages /Count %d /Kids [%s] >>", len(pages), strings.Join(kids, " "))
	objects[3] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"
	objects[4] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>"

	var out bytes.Buffer
	out.WriteString("%PDF-1.4\n%\xFF\xFF\xFF\xFF\n")
	offsets := make([]int, maxID+1)
	for id := 1; id <= maxID; id++ {
		offsets[id] = out.Len()
		fmt.Fprintf(&out, "%d 0 obj\n%s\nendobj\n", id, objects[id])
	}
	xrefOffset := out.Len()
	fmt.Fprintf(&out, "xref\n0 %d\n", maxID+1)
	out.WriteString("0000000000 65535 f \n")
	for id := 1; id <= maxID; id++ {
		fmt.Fprintf(&out, "%010d 00000 n \n", offsets[id])
	}
	fmt.Fprintf(&out, "trailer << /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF", maxID+1, xrefOffset)
	return out.Bytes()
}

func buildPDFContent(lines []pdfLine, watermark string, pageNumber, pageCount, leftMargin, topStartY int) string {
	var b strings.Builder
	b.WriteString("q 0.92 g BT /F2 28 Tf 110 420 Td (")
	b.WriteString(escapePDFText(watermark))
	b.WriteString(") Tj ET Q\n")
	y := topStartY
	for _, line := range lines {
		font := "F1"
		if line.bold {
			font = "F2"
		}
		size := line.fontSize
		if size <= 0 {
			size = 10
		}
		fmt.Fprintf(&b, "BT /%s %d Tf 0 g %d %d Td (%s) Tj ET\n", font, size, leftMargin, y, escapePDFText(line.text))
		switch {
		case size >= 16:
			y -= 22
		case size >= 12:
			y -= 18
		case size <= 9:
			y -= 12
		default:
			y -= 14
		}
	}
	fmt.Fprintf(&b, "BT /F1 9 Tf 0 g 42 24 Td (Page %d / %d) Tj ET\n", pageNumber, pageCount)
	return b.String()
}

func escapePDFText(value string) string {
	replacer := strings.NewReplacer(
		"\\", "\\\\",
		"(", "\\(",
		")", "\\)",
		"\r", " ",
		"\n", " ",
	)
	return replacer.Replace(value)
}

func truncatePDFLine(value string, maxRunes int) string {
	runes := []rune(strings.TrimSpace(value))
	if len(runes) <= maxRunes {
		return string(runes)
	}
	return string(runes[:maxRunes-1]) + "…"
}

func buildArchiveReportID(kind WerkaArchiveKind) string {
	code, _ := buildArchiveVerifyCode()
	suffix := strings.ReplaceAll(code, "-", "")
	if len(suffix) > 4 {
		suffix = suffix[:4]
	}
	return fmt.Sprintf("WAR-%s-%s-%s", strings.ToUpper(string(kind)), time.Now().Format("20060102-150405"), suffix)
}

func buildArchiveVerifyCode() (string, error) {
	raw := make([]byte, 8)
	if _, err := rand.Read(raw); err != nil {
		return "", err
	}
	token := strings.TrimRight(base32.StdEncoding.EncodeToString(raw), "=")
	token = strings.ToUpper(token)
	if len(token) < 12 {
		return token, nil
	}
	return fmt.Sprintf("%s-%s-%s", token[:4], token[4:8], token[8:12]), nil
}

func archiveReportTitle(kind WerkaArchiveKind) string {
	switch kind {
	case WerkaArchiveKindReceived:
		return "Werka Qabul Qilingan Hisoboti"
	case WerkaArchiveKindReturned:
		return "Werka Qaytarilgan Hisoboti"
	default:
		return "Werka Jo'natilgan Hisoboti"
	}
}

func archivePeriodTitle(period WerkaArchivePeriod) string {
	switch period {
	case WerkaArchivePeriodDaily:
		return "Kunlik"
	case WerkaArchivePeriodMonthly:
		return "Oylik"
	default:
		return "Yillik"
	}
}
